NO_ERROR		= 0

ERROR_SUCCESS	= 0

ERROR_ALREADY_EXISTS    		= 183
ERROR_CONNECTION_INVALID        = 1229
ERROR_INVALID_PARAMETER         = 87
ERROR_INSUFFICIENT_BUFFER       = 122
ERROR_MORE_DATA                 = 234
ERROR_NOACCESS                  = 998
ERROR_HANDLE_EOF                = 38
