NO_ERROR		= 0;

ERROR_SUCCESS	= 0;

ERROR_INVALID_FUNCTION          = 1;    

ERROR_FILE_NOT_FOUND            = 2;

ERROR_ACCESS_DENIED             = 5;

ERROR_INVALID_HANDLE            = 6;

ERROR_INVALID_DATA              = 13;

ERROR_HANDLE_EOF                = 38;

ERROR_NOT_SUPPORTED             = 50;

ERROR_INVALID_PARAMETER         = 87;

ERROR_INSUFFICIENT_BUFFER       = 122;

ERROR_INVALID_NAME              = 123;

ERROR_ALREADY_EXISTS    		= 183;

ERROR_ENVVAR_NOT_FOUND          = 203;

ERROR_MORE_DATA                 = 234;

ERROR_NOACCESS                  = 998;

ERROR_INVALID_SERVICE_CONTROL   = 1052;

ERROR_CONNECTION_INVALID        = 1229;

ERROR_PRIVILEGE_NOT_HELD        = 1314;

ERROR_LOGON_FAILURE             = 1326;

ERROR_LOGON_TYPE_NOT_GRANTED    = 1385;
