NO_ERROR		= 0

ERROR_SUCCESS	= 0

ERROR_ACCESS_DENIED             = 5;

ERROR_HANDLE_EOF                = 38;

ERROR_NOT_SUPPORTED             = 50;

ERROR_INVALID_PARAMETER         = 87;

ERROR_INSUFFICIENT_BUFFER       = 122;

ERROR_ALREADY_EXISTS    		= 183;

ERROR_MORE_DATA                 = 234;

ERROR_NOACCESS                  = 998;

ERROR_INVALID_SERVICE_CONTROL   = 1052;

ERROR_CONNECTION_INVALID        = 1229;
